#!/usr/bin/env ruby

files_and_dirs = Dir.glob("*", File::FNM_DOTMATCH) - %w[. .. install .git .DS_Store]

files_and_dirs.each do |file_or_dir|
  cmd = "cp -r ./#{file_or_dir} ~/."
  %x[ #{cmd} ]
end
