#!/usr/bin/env ruby

files = Dir.glob("*", File::FNM_DOTMATCH) - %w[. .. install .git 
  .DS_Store Library README.md update .config .vim]

files.each do |file_or_dir|
  cmd = "cp -r ~/#{file_or_dir} ."
  %x[ #{cmd} ]
end

nested_files = {
  '.config/karabiner': 'karabiner.json',
  '.config/nvim': 'init.vim',
  '.vim': 'vimrc',
  '.vim/autoload': 'plug.vim'
}

nested_files.each do |dir, file|
  cmd = "mkdir -p #{dir} && cp ~/#{dir}/#{file} #{dir}"
  %x[ #{cmd} ]
end


