" Set leader key to space
let mapleader=" "
let maplocalleader=" "

call plug#begin()

  Plug 'dense-analysis/ale'

  Plug 'ternjs/tern_for_vim', {'do': 'npm install'}

  Plug 'carlitux/deoplete-ternjs', { 'do': 'npm install -g tern' }

  if has('nvim')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  else
    Plug 'Shougo/deoplete.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
  endif

  Plug 'itchyny/lightline.vim'

  Plug 'scrooloose/nerdcommenter'

  Plug 'scrooloose/nerdtree'

  Plug 'haishanh/night-owl.vim'

  " nvim-typescript
  Plug 'HerringtonDarkholme/yats.vim'
  Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
  " For Denite features
  Plug 'Shougo/denite.nvim'

  Plug 'mattn/emmet-vim'

  Plug 'leafgarland/typescript-vim'

  Plug 'peitalin/vim-jsx-typescript'

  Plug 'tpope/vim-fugitive'

  Plug 'tpope/vim-rhubarb'

  Plug 'prettier/vim-prettier', { 'do': 'npm install' }
  
  Plug 'HerringtonDarkholme/yats.vim'

  Plug 'yuttie/comfortable-motion.vim'

  Plug 'mileszs/ack.vim'

  Plug 'powerman/vim-plugin-autosess'

call plug#end()

""""" enable 24bit true color

" If you have vim >=8.0 or Neovim >= 0.1.5
if (has("termguicolors")) 
 set termguicolors
endif

" Check if any buffers were changed outside of vim every time the cursor stops
" moving
au CursorHold,CursorHoldI * checktime

" For Neovim 0.1.3 and 0.1.4
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

""""" enable the theme
colorscheme night-owl

" Enable mouse scrolling
set mouse=a

" Highlight current line
set cursorline

" Map 0 to ^ to use 0 to move to first non-blank character
map 0 ^

set colorcolumn=120

set number

set hidden

" Save 1,000 items in history
set history=1000

" Display the incomplete commands in the bottom right-hand side     of your screen.                                         
set showcmd

" Display completion matches on your status line
set wildmenu

" Display completion matches on your status line
set wildmenu

" Enable incremental searching
set incsearch

" Ignore case when searching
set ignorecase

" Override the 'ignorecase' option if the search pattern contai    ns upper case characters.                                
set smartcase

" Don't line wrap mid-word.
set lbr

" Copy the indentation from the current line.
set autoindent

" Enable smart autoindenting.
set smartindent

" Use spaces instead of tabs
set expandtab

" Enable smart tabs
set smarttab

" Make a tab equal to 4 spaces
set shiftwidth=2
set tabstop=2

set timeoutlen=500 ttimeoutlen=0

" Change cursor on insert mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
" optional reset cursor on start:
augroup myCmds
au!
autocmd VimEnter * silent !echo -ne "\e[2 q"
augroup END

" When running search, highlight found words
set hlsearch

" Clear highlighting on escape in normal mode
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

" Close quickfix and preview windows
nnoremap <Leader>X :ccl<CR>:pc<CR>

" Search word under cursor with leader-f
nnoremap <Leader>f #

" Save and quit shortcuts
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>

" Tabbing shortcuts 
nnoremap <Leader>t :tabnew<CR>
nnoremap <Leader>x :tabclose<CR>
nnoremap <Leader>[ :tabp<CR>
nnoremap <Leader>] :tabn<CR>
nnoremap <Leader>{ :tabm -1<CR>
nnoremap <Leader>} :tabm +1<CR>

" Move back and forth between two files by pressing the leader key twice
nnoremap <Leader><Leader> :e#<CR>

" Show matching parentheses
set showmatch

" NERD Commenter settings
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1
" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1

" Lightline config
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }
let g:lightline = {
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ }
      \ }
function! LightlineFilename()
  let root = fnamemodify(get(b:, 'git_dir'), ':h')
  let path = expand('%:p')
  if path[:len(root)-1] ==# root
    return path[len(root)+1:]
  endif
  return expand('%')
endfunction

" NERDTree config
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
 exec 'autocmd filetype nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
 exec 'autocmd filetype nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction
call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')
let NERDTreeShowHidden=1
nmap <leader>n :NERDTreeToggle %<CR>
nmap <leader>j :NERDTreeFind<CR>
let NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp']

" fzf config
nnoremap <Leader>p :FZF<CR>
" Add fzf to runtimepath
if has('macunix')
  set rtp+=/usr/local/opt/fzf
elseif has('unix')
  set rtp+=~/.fzf
endif

" deoplete config
let g:deoplete#enable_at_startup = 1
"Add extra filetypes
let g:deoplete#sources#ternjs#filetypes = [
                \ 'jsx',
                \ 'javascript.jsx',
                \ 'vue',
                \ ]
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]

" ALE config
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'typescript': ['tsserver', 'tslint', 'eslint'],
\   'vue': ['eslint']
\}
let g:ale_fixers = {
\    'javascript': ['eslint'],
\    'typescript': ['prettier', 'tslint', 'eslint'],
\    'vue': ['eslint'],
\    'scss': ['prettier'],
\    'css': ['prettier'],
\    'html': ['prettier']
\}
let g:ale_fix_on_save = 1
nmap <leader>d :ALEGoToDefinitionInTab<CR>
nmap <leader>r :ALEFindReferences<CR>

" emmet config
let g:user_emmet_leader_key='<Tab>'
autocmd FileType html,css,javascript.jsx EmmetInstall
" let g:user_emmet_settings = {
  " \  'javascript.jsx' : {
    " \      'extends' : 'jsx',
    " \  },
  " \}

" ack.vim config
cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>
noremap <Leader>F :Ack <cword><cr>
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

